# CI-specific Nginx configuration
pid /tmp/nginx.pid;
error_log /tmp/error.log;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    access_log /tmp/access.log;

    server {
        listen 3000;

        # We serve frontend from the GITHUB_WORKSPACE location
        location /report/ {
            alias $FRONTEND_PATH; # Use $FRONTEND_PATH which we will inject during the CI step in workflow yml file
            index index.html;
        }

        # Backend proxy
        location /tud_backend/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
        }
    }
}